### PR TITLE
Use released version instead of unstable latest

### PR DESCRIPTION
**Pull request by oserban**

### CODE REVIEW

**Comment by davidbirchwork** [comment]
could we provide a Dev and a Release version of this script? (e.g. a build all from local sources)

**Comment by senakafdo** [comment]
> could we provide a Dev and a Release version of this script? (e.g. a build all from local sources)

It will need to support several release versions along with the `latest` version, ideally. But, before that, we will probably have to define some sort of system-wide version.

**Comment by oserban** [comment]
The release version of this script is the current pull request. I agree that having dev scripts may be a very good idea, but the documentation **should** refer to the stable scripts anyway ...

**Comment by senakafdo** [comment]
> The release version of this script is the current pull request. I agree that having dev scripts may be a very good idea, but the documentation **should** refer to the stable scripts anyway ...

The documentation cannot be written to suit something that is not properly thought through. Let me explain the complete problem such that it is crystal clear.

The documentation will also be versioned. So, currently these scripts stand at 0.2 of OVE/OVE-Apps and latest of everything else. Now, assume we release OVE/OVE-Apps 0.3. If we simply update these scripts to 0.3, the documentation corresponding to the latest release will work well. However the documentation written for the 0.2 release will not continue to be accurate at that point.

Even worse, there is no possibility that someone can test an upcoming release in this model, as this requires everything to be released first and then fixed, which creates further releases to fix any issues uncovered during testing.

This is why we need an equivalent of a `release matrix` and the installers should be able to combine multiple versions of components on that matrix. The matrix **should not exclude latest**. The objective of the installer is not to avoid someone installing the latest code.

**Pull request merged**
