### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by oserban**
I am disabling the Windows Builds as Travis does not seem to fix them. It's useless to build these things atm and ti's a waste of energy

### CODE REVIEW

**Comment by senakafdo** [comment]
We discussed this (guess you were there too), and the answer was to use [Azure pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) for the OVE builds. This is a tweak. And, I am not very happy with this fix.

**Comment by oserban** [comment]
@senakafdo there were failing builds on some PR of this repo, which we ignored because this repo is failing all the time. It's not constructive to leave it failing ...

**Comment by senakafdo** [comment]
@oserban, it is incorrect to say that builds are failing. The Linux and MacOS builds are passing on this repo and they also deploy the release artefacts accurately. The only difference your fix makes is that `you get a ✅ instead of a ❌ in the status`. And, in reality you achieve that by commenting out a perfectly accurate Travis script. So, if you want to truly fix this, you can either motivate Travis.ci folks or switch to [Azure pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/).

**Comment by jamesscottbrown** [comment]
> @oserban, it is incorrect to say that builds are failing

build-failed

Travis says 'Build Failed'...

**Comment by oserban** [comment]
Until I wait for an answer from Travis team on my request to fix their build system for Windows, which I am sure they'll listen. Can we please get this approved so we no longer have a failing build ?

**Comment by senakafdo** [comment]
@jamesscottbrown, see https://travis-ci.com/ove/ove-install/builds/108276051, "Jobs and Stages" of https://github.com/ove/ove-install/pull/35/checks?check_run_id=101383951, and https://github.com/ove/ove-install/releases corresponding to the builds that pass.

@oserban, I have made that request along with many others, https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/10. And, they have done nothing on this since October 2018. Perhaps they will listen to you and fix it in "X"-number-of-days, but OTOH, if you switch to Azure pipelines, it will work from now onwards.

**Comment by senakafdo** [comment]
FTR, watch, https://dev.azure.com/tsf114/ove/.

**Comment by oserban** [comment]
@senakafdo you just gave yourself the final argument to approve this PR. As you said, Travis does not have the capacity to fix the Windows build problems so ... we need to disable the Windows builds on Travis CI (the current PR) and implement the same pipeline on Azure builds (which is another feature -> another PR). The current PR just disables the Windows PR on Travis which are broken and do not produce any output ...

**Comment by senakafdo** [comment]
@oserban, alright, I will migrate this to Azure pipelines. If I cannot do this in a timely manner I will fallback and approve your PR - agreed?

If you are intolerant of this viewpoint, you too could help implement the build in Azure pipelines, :). I am more than happy to have you onboard.

**Comment by oserban** [comment]
@senakafdo you can approve this PR which disables the Windows builds and then take as much time as you need to migrate the Windows build on Azure pipelines. I think, in my humble professional opinion, this is the safest way to go ...

**Comment by jamesscottbrown** [comment]
In my opinion, [this commit](https://github.com/ove/ove-install/commit/e84000ba72f5f605d0d1fcfabb6fba7de7c2d54b#diff-354f30a63fb0907d4ad57269548329e3) should have never made it to master, because it got the Travis configuration into a broken state where it always reports Build Failure.

I agree with @oserban that we should revert it and remove the windows build, as this does not work (and has never worked).

We can implement a working Windows build in Azure, but there is no reason to wait for this before fixing the Travis configuration that currently exists.

**Pull request closed without merging**
