### PR TITLE
Setup.py

### PR DESCRIPTION
**Pull request by oserban**

### CODE REVIEW

**Comment by jamesscottbrown** [comment]
> There was one warning, which I suppose is harmless, WARN: unable to check whether docker and docker-compose are installed. What should be done differently to avoid this warning?

I have fixed this.

**Comment by senakafdo** [comment]
> > There was one warning, which I suppose is harmless, WARN: unable to check whether docker and docker-compose are installed. What should be done differently to avoid this warning?
> 
> I have fixed this.

Thanks, what is pending are the bits related to version numbers.

**Comment by jamesscottbrown** [comment]
The README should explain that building the python script is not necessary unless you are packaging it to be run on a machine that does not have python installed: if you have python installed, you can just run `python setup.py` as a single step.

**Comment by senakafdo** [comment]
The fact that we use `setup.py` to produce `dist/setup` is slightly confusing too. Is it possible to rename `setup.py` to `configure.py` and `dist/setup` to `dist/make`? People are generally familiar with the `configure -> make -> install` process.

**Comment by senakafdo** [comment]
> The README should explain that building the python script is not necessary unless you are packaging it to be run on a machine that does not have python installed: if you have python installed, you can just run `python setup.py` as a single step.

Ok, if we do that then there may be no need of renaming these as configure.py and make, which was to avoid the confusion. It would be best to update the README either way.

**Comment by oserban** [comment]
> The fact that we use `setup.py` to produce `dist/setup` is slightly confusing too. Is it possible to rename `setup.py` to `configure.py` and `dist/setup` to `dist/make`? People are generally familiar with the `configure -> make -> install` process.

I think renaming the tool/script into make will make this incredibly confusing. Make is a standard build tool for linux. Install assumes that we are going to install some packages where the setup.py script just generates a config.

**Comment by oserban** [comment]
I also agree with @jamesscottbrown that building the script is not required, but I thought that this is the whole point of the process to give users a tool to generate their docker-compose startup scripts.

On the other hand, I don't understand how the version template would be included/integrated in the setup script. When we discussed/debated these issues, we agreed that the setup script will suggest the latest stable version for every component, not every compatible version. If someone wants to build their own custom setup with versions different from the latest, they'll have to look at the compatibility table themselves and select whatever version they wish to deploy.

**Comment by senakafdo** [comment]
> > The fact that we use `setup.py` to produce `dist/setup` is slightly confusing too. Is it possible to rename `setup.py` to `configure.py` and `dist/setup` to `dist/make`? People are generally familiar with the `configure -> make -> install` process.
> 
> I think renaming the tool/script into make will make this incredibly confusing. Make is a standard build tool for linux. Install assumes that we are going to install some packages where the setup.py script just generates a config.

So, I'm ok with updating the README, for this. My point was that we have a `setup.py` and `setup` is utterly confusing for anyone except for the person who designed it. They'd obviously be able to tell the difference.

**Comment by senakafdo** [comment]
> I also agree with @jamesscottbrown that building the script is not required, but I thought that this is the whole point of the process to give users a tool to generate their docker-compose startup scripts.
> 
> On the other hand, I don't understand how the version template would be included/integrated in the setup script. When we discussed/debated these issues, we agreed that the setup script will suggest the latest stable version for every component, not every compatible version. If someone wants to build their own custom setup with versions different from the latest, they'll have to look at the compatibility table themselves and select whatever version they wish to deploy.

So, the version template is not for `dist/setup`. It is for the `setup.py`, and used when you want to build the `dist/setup` from `setup.py` you will therefore not need to modify version numbers, and the person making the release has a clearly defined process of making the latest into a release version and introducing a new latest. This is very handy when you need to iterate from latest through to x.y.z-beta, x.y.z-RC to x.y.z. I am happy to update the setup.py to use pyyaml to allow this.

**Comment by senakafdo** [comment]
@oserban, @jamesscottbrown I have fixed the issues that I have raised.

Given how `pyinstaller` works, I found that it is just unwanted complexity to have a `configure.py` to distinguish it from `dist/setup`. Given that the majority of our end-users would not be using `setup.py` I thought it is best to leave the filenames as-is.

@jamesscottbrown, if you are able to, please do test my fixes on Python 2.7 and Python 3. I have a blend of both Python versions on my Mac and I'm not 100% sure which combination is being used when.

**Comment by senakafdo** [comment]
BTW, are you supposed to run setup in Windows? 

If so, a few things may need fixing, such as [`--add-data` uses `os.pathsep`](https://pyinstaller.readthedocs.io/en/v3.3.1/usage.html#options-group-what-to-bundle-where-to-search)

**Comment by senakafdo** [comment]
@oserban, I have tested the build on **Windows 8.1** using **Python 3.7.2** and I can confirm that it works well. However, there is one issue, the command window closes before the user can read the final instructions on how to run the generated docker compose files. We should perhaps introduce a `press ENTER to continue` line at the end of our script?

**Comment by oserban** [comment]
That part of the original script, but @jamesscottbrown removed that line as he considered it useless. You can talk to him and revert that change. I think pausing at the end of the script is a good idea.

**Comment by miguems** [comment]
> @jamesscottbrown, would we be able to reintroduce the `Press any key to exit ...` block that you got rid of in [772c3c5](https://github.com/ove/ove-install/commit/772c3c5aa104a1c2c8a52a63d2118bc498b1d20b)?

If you launch the script with double click, not having that last instruction is a problem (because the window closes as soon as it finishes). However, when the script is run from a terminal, the terminal is not closed automatically, so you can see the message without problems (and hence do not need the "press any key"). 

As most windows user will use the double click, I think having that last instruction is useful, and in any case, having it makes no harm.

**Comment by senakafdo** [comment]
> I'm not sure whether this is true in this specific case, as they will run this script immediately before running docker-compose, which will need to be done at a terminal anyway.

@jamesscottbrown, what we have is a `setup.exe`. And, any _ordinary_ Windows user would run it by double clicking it. Of course they would not be running docker-compose in such a way.

+1 for including `input("Press Enter to exit")`

**Comment by senakafdo** [comment]
@jamesscottbrown, @oserban, @miguems, alright I have fixed it.

**Comment by jamesscottbrown** [comment]
> Of course they would not be running docker-compose in such a way.

AFAIU, that is *exactly* what they will be doing: our installation process is to run this script (or the compiled ,exe produced from it), *and then to use the `docker-compose` command at the command line*.

**Comment by senakafdo** [comment]
> AFAIU, that is *exactly* what they will be doing: our installation process is to run this script (or the compiled ,exe produced from it), *and then to use the `docker-compose` command at the command line*.

Sorry for any confusion. What I meant is that they would not run docker-compose by double clicking it.

**Pull request merged**
